services:
  traefik:
    image: traefik:@latest
    container_name: traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      # EntryPoints
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --entrypoints.websecure.address=:443

      # Enable HTTPS using Let's Encrypt
      - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
      - --certificatesresolvers.mytlschallenge.acme.email=admin@myapp.example.com
      - --certificatesresolvers.mytlschallenge.acme.storage=/etc/traefik/acme.json
      # OPTIONAL: use staging (uncomment for testing only)
      # - --certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory

      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
    restart: unless-stopped

  server:
    image: myapp/server:latest
    environment:
      # Server Configuration
      NODE_ENV: production
      PORT: 3001

      # Database Configuration
      DATABASE_URL: postgres://user:password@postgres:5432/library

      # JWT Secret - IMPORTANT: Change this in production!
      # Generate one using: openssl rand -hex 32
      JWT_SECRET: "CHANGE_THIS_IN_PRODUCTION"

      # Google Books API (Optional)
      # Get your API key from: https://console.cloud.google.com/apis/credentials
      GOOGLE_BOOKS_API_KEY: ""

      # Client URL (for CORS)
      CLIENT_URL: "https://myapp.example.com"

      # Email/SMTP Configuration (Optional)
      # Set to 'true' to enable email notifications
      ENABLE_EMAIL_NOTIFICATIONS: "false"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_SECURE: "false"
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "library@example.com"

      # Overdue Notifications
      # Set to 'false' to disable overdue checks
      ENABLE_OVERDUE_CHECKS: "true"
      OVERDUE_CHECK_INTERVAL: "60"
    volumes:
      - uploads_data:/app/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`myapp.example.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=mytlschallenge"
      - "traefik.http.services.server.loadbalancer.server.port=3001"
    depends_on:
      - postgres
    restart: unless-stopped

  client:
    image: myapp/client:latest
    environment:
      # API Configuration
      # Change to your domain: https://your-domain.com/api
      VITE_API_URL: "https://myapp.example.com/api"

      # Library Branding
      # Customize your library name and logo
      VITE_LIBRARY_NAME: "My Library"
      # Use a local path or external URL for the logo
      VITE_LIBRARY_LOGO: "/Logo.svg"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`myapp.example.com`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=mytlschallenge"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
    depends_on:
      - server
      - traefik
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  uploads_data:
  db_backups:
