# Docker Compose for GitHub Container Registry Images
#
# This configuration uses pre-built images from GitHub Container Registry.
# No local build required - just pull and run!
#
# Usage:
#   1. Copy .env.example files to .env and configure
#   2. Run: docker-compose -f compose.ghcr.yml up -d
#   3. Access: http://localhost:3000
#
# To use your own fork:
#   - Replace 'yourusername' with your GitHub username
#   - Make sure your images are public or you're logged in:
#     docker login ghcr.io -u YOUR_GITHUB_USERNAME
#
# Image tags:
#   - latest: Latest build from main branch
#   - v1.0.0: Specific version tags
#

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d library"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    # Change 'yourusername' to your GitHub username/organization
    image: ghcr.io/yourusername/homeshelf-server:latest
    restart: unless-stopped
    environment:
      # Server Configuration
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3001

      # Database Configuration
      DATABASE_URL: postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/library

      # JWT Secret - REQUIRED: Change this!
      # Generate with: openssl rand -hex 32
      JWT_SECRET: ${JWT_SECRET}

      # Google Books API (Optional)
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY:-}

      # Client URL (for CORS)
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}

      # Email Configuration (Optional)
      ENABLE_EMAIL_NOTIFICATIONS: ${ENABLE_EMAIL_NOTIFICATIONS:-false}
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_FROM: ${SMTP_FROM:-library@example.com}

      # Overdue Notifications
      ENABLE_OVERDUE_CHECKS: ${ENABLE_OVERDUE_CHECKS:-true}
      OVERDUE_CHECK_INTERVAL: ${OVERDUE_CHECK_INTERVAL:-60}
    ports:
      - "${SERVER_PORT:-3001}:3001"
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  client:
    # Change 'yourusername' to your GitHub username/organization
    image: ghcr.io/yourusername/homeshelf-client:latest
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local
