# Use official Node image
FROM node:24-alpine

# Create app directory
WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Copy only dependency files first
COPY package*.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the application
COPY . .

# Expose backend port
EXPOSE 3001

# Start backend
CMD ["pnpm", "start"]
